### ISSUE TITLE
Clean up OpenAI Schema in Yaml file to avoid related log errors

### ISSUE THREAD

**Issue by hatgit** [hatgit/forex-gpt#5]
while these deployment errors on Railway app likely related to Open AI .yaml Schema and not causing the app to misbehave, they should be fixed nonetheless:

```
192.168.0.3 - - [14/Nov/2023 14:50:52] "GET /openapi.yaml HTTP/1.1" 200 -

[2023-11-14 14:50:52,833] ERROR in app: Exception on /search [POST]

Traceback (most recent call last):

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app

response = self.full_dispatch_request()

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/opt/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request

rv = self.dispatch_request()

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request

return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

File "main.py", line 97, in search

response = openai.Completion.create(

AttributeError: module 'openai' has no attribute 'Completion'

192.168.0.3 - - [14/Nov/2023 14:50:52] "POST /search HTTP/1.1" 500 -

192.168.0.4 - - [14/Nov/2023 14:51:55] "GET /logo.png HTTP/1.1" 200 -

192.168.0.2 - - [14/Nov/2023 14:52:03] "GET /logo.png HTTP/1.1" 304 -

192.168.0.2 - - [14/Nov/2023 14:52:11] "GET /logo.png HTTP/1.1" 200 -

192.168.0.3 - - [14/Nov/2023 14:52:53] "GET /logo.png HTTP/1.1" 304 -
```

Potential Fix: replace existing yaml file with this one: 

```
openapi: 3.0.1
info:
  title: Forex Prices powered by OpenAI
  description: Unleash Forex GPT; Advanced analysis for currency markets. Gain insights, sentiment evaluation, and text completion.
  version: 'v1'
servers:
  - url: https://live.forex-gpt.ai
oanda:
  hostname: api-fxpractice.oanda.com
  streaming_hostname: stream-fxpractice.oanda.com
  port: 443
  ssl: true
  token: YOUR_OANDA_TOKEN
  username: YOUR_OANDA_USERNAME
  accounts:
    - YOUR_ACCOUNT_ID_1
    - YOUR_ACCOUNT_ID_2
  active_account: YOUR_ACTIVE_ACCOUNT_ID
paths:
  /analyze:
    post:
      operationId: analyze
      summary: Analyze text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/analyzeRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/analyzeResponse'
  /generate:
    post:
      operationId: generate
      summary: Generate text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/generateRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generateResponse'
  /complete:
    post:
      operationId: complete
      summary: Complete text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/completeRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/completeResponse'
  /search:
    post:
      operationId: search
      summary: Search for text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/searchRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchResponse'
  /playground:
    post:
      operationId: playground
      summary: Use the OpenAI playground
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/playgroundRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/playgroundResponse'
  /prices:
    post:
      operationId: prices
      summary: Get historical prices from the OANDA API
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pricesRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pricesResponse'
components:
  schemas:
    analyzeRequest:
      type: object
      required: 
        - text
      properties:
        text:
          type: string
          description: The text to analyze.
        entities:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                description: The type of entity.
              start:
                type: integer
                description: The start index of the entity.
              end:
                type: integer
                description: The end index of the entity.
              text:
                type: string
                description: The text of the entity.
    analyzeResponse:
      type: object
      properties:
        sentiment:
          type: string
          description: The overall market sentiment based on the analysis.
        smas:
          type: object
          additionalProperties:
            type: number
          description: A dictionary of Simple Moving Averages (SMAs) for various periods.
        error:
          type: string
          description: Error message in case the analysis fails.
    generateRequest:
      type: object
      required: 
        - prompt
      properties:
        prompt:
          type: string
          description: The prompt for the generator.
        temperature:
          type: number
          format: float
          description: The temperature of the generator.
          default: 0.5
    generateResponse:
      type: object
      properties:
        generated_text:
          type: string
          description: The generated text.
    completeRequest:
      type: object
      required: 
        - text
      properties:
        text:
          type: string
          description: The text to complete.
    completeResponse:
      type: object
      properties:
        completed_text:
          type: string
          description: The completed text.
    searchRequest:
      type: object
      required: 
        - query
      properties:
        query:
          type: string
          description: The search query.
    searchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
                description: The title of the search result.
              url:
                type: string
                description: The URL of the search result.
    playgroundRequest:
      type: object
      required: 
        - code
      properties:
        code:
          type: string
          description: The code to execute in the OpenAI playground.
    playgroundResponse:
      type: object
      properties:
        output:
          type: string
          description: The output of the code execution in the OpenAI playground.
    pricesRequest:
      type: object
      required: 
        - instrument
        - from_time
        - granularity
        - price
      properties:
        instrument:
          type: string
          description: The instrument to get historical prices for.
        from_time:
          type: string
          description: The start time for retrieving historical prices.
        granularity:
          type: string
          description: The granularity of the historical prices.
        price:
          type: string
          description: The price type to retrieve (e.g., BA, BC, BO).
    pricesResponse:
      type: object
      properties:
        prices:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: string
                description: The timestamp of the price.
              bid:
                type: object
                properties:
                  o:
                    type: string
                    description: The open bid price.
                  h:
                    type: string
                    description: The high bid price.
                  l:
                    type: string
                    description: The low bid price.
                  c:
                    type: string
                    description: The close bid price.
              ask:
                type: object
                properties:
                  o:
                    type: string
                    description: The open ask price.
                  h:
                    type: string
                    description: The high ask price.
                  l:
                    type: string
                    description: The low ask price.
                  c:
                    type: string
                    description: The close ask price.

```

**Comment by hatgit** [comment]
The above proposed replacement for the yaml file was added in [this merge](https://github.com/hatgit/forex-gpt/commit/013c0267bccaeacd48981b9e522535cb2d7f9264), and the following errors remain as per Railway app deployment logs (which reference a [github guide to upgrade](https://github.com/openai/openai-python/discussions/742) the affected module): 

```
192.168.0.4 - - [14/Nov/2023 15:26:04] "GET /openapi.yaml HTTP/1.1" 200 -

[2023-11-14 15:26:05,285] ERROR in app: Exception on /generate [POST]

Traceback (most recent call last):

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app

response = self.full_dispatch_request()

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request

rv = self.handle_user_exception(e)

File "/opt/venv/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function

return cors_after_request(app.make_response(f(*args, **kwargs)))

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request

rv = self.dispatch_request()

File "/opt/venv/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request

return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

File "main.py", line 70, in generate

generated_text = openai.ChatCompletion.create(engine="gpt-4-1106-preview",

File "/opt/venv/lib/python3.8/site-packages/openai/_utils/_proxy.py", line 22, in __getattr__

return getattr(self.__get_proxied__(), attr)

File "/opt/venv/lib/python3.8/site-packages/openai/_utils/_proxy.py", line 43, in __get_proxied__

return self.__load__()

File "/opt/venv/lib/python3.8/site-packages/openai/lib/_old_api.py", line 33, in __load__

raise APIRemovedInV1(symbol=self._symbol)

openai.lib._old_api.APIRemovedInV1:

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

192.168.0.2 - - [14/Nov/2023 15:26:05] "POST /generate HTTP/1.1" 500 -

192.168.0.2 - - [14/Nov/2023 15:26:07] "GET /logo.png HTTP/1.1" 200 -

192.168.0.3 - - [14/Nov/2023 15:26:37] "GET /logo.png HTTP/1.1" 200 -

192.168.0.2 - - [14/Nov/2023 15:26:53] "GET /logo.png HTTP/1.1" 200 -

192.168.0.2 - - [14/Nov/2023 15:27:37] "GET /logo.png HTTP/1.1" 200 -

192.168.0.3 - - [14/Nov/2023 15:28:36] "GET /logo.png HTTP/1.1" 200 -

192.168.0.4 - - [14/Nov/2023 15:28:54] "GET /robots.txt HTTP/1.1" 404 -

192.168.0.4 - - [14/Nov/2023 15:29:07] "GET /logo.png HTTP/1.1" 200 -

192.168.0.3 - - [14/Nov/2023 15:29:19] "GET /logo.png HTTP/1.1" 200 -
```

**Comment by hatgit** [comment]
This issue was related to an upgraded version of OpenAI's python code as per this migration manual: https://github.com/openai/openai-python/discussions/742 and has since been resolved since we upgraded with the above commit which is now closed/fixed.
